### ISSUE TITLE
Group Billing Q/A

### ISSUE THREAD

**Issue by dzucconi** [aredotna/ervell#1638]
- [x] Change non-toggled state of cancel buttons to say "Don't cancel"
- [x] Change "Already premium" members that you pay for to _____

**Comment by danpia** [comment]
- [ ] my group was "Everyone in your group is premium :)" > I added Cab Style to the group > the interface switched to (see screenshot below) which is misleading because looks like _no one_ is premium. We probably need a similar blue message saying "2 out of 3 members are already Premium"
<img width="745" alt="screen shot 2019-01-03 at 12 16 22 pm" src="https://user-images.githubusercontent.com/3718189/50651551-be3dce80-0f51-11e9-8b7b-04e97387fa60.png">

- [ ] display myself (the admin) in the billing members modal either if I'm Premium or not. If not Premium a message should communicate to upgrade via individual billing:
<img width="623" alt="screen shot 2019-01-03 at 1 41 51 pm" src="https://user-images.githubusercontent.com/3718189/50655226-78870300-0f5d-11e9-8da5-99d95f5a3fff.png">

**Comment by csherron** [comment]
- [ ] after subscribing my users to premium on a group, its position on the page shifts second last >> second in the group list, not a huge deal but disorienting
- [ ] the blue ‘subscribed! you’re all set’ alert persists, should disappear after a bit
- [ ] need an orange alert bar showing confirmation of cancelling members “Subscription(s) canceled” (currently it shows the “subscribed you’re all set” alert, which is wrong
- [ ] make the “+ Add credit card” link a button
- [ ] auto-select the first form field when opening the “billed to” credit card form modal
- [ ] after selecting one member using the toggle modal and upgrading them, the blue box copy returns to selecting everybody again, and the CTA says “activate X premium subscriptions” (X=# of total non-premium members) - after upgrading, the selected members should persist and the CTA remain inactive
- [ ] after upgrading members then refreshing the page > the radio has ‘don’t upgrade’ selected - and the only indication of me paying is the ‘cancel premium link’ - no indication of how much i’m paying or who i’m paying for - instead the radio should have the monthly or yearly radio selected with the # of individuals i have currently upgraded in the blue box + deactivated CTA (until i decide to add or cancel others)
