### ISSUE TITLE
Deployable Homepage Q/A

### ISSUE THREAD

**Issue by dzucconi** [aredotna/ervell#692]
Re (logged out): http://staging.are.na

## Critical
- [x] Fix for relative border sizes (normalize across Safari)
- [x] Fix blog layout regression
- [x] Retain original hover state when moving to connect button hover state (border, attribution)
- [x] header: change “Join Login” to “Join or Log In”
- [x] get rid of “updated X ago” in block captions
- [x] “what is arena?” - make h5 and strong, with 2em padding instead of 1
- [x] .utility—bordered give it a 1px border #c6c6c6
- [x] video borders flicker and disappear on safari
- [x] .HomeNext - bottom: 2em; make #c6c6c6
- [x] ‘explore and collaborate’ section - replace still image with ‘onboarding-explore’ video, keep border
- [x] ‘explore and collaborate’ section is wider set than the other sections

## Auth
- [x] in signup form, change “sign up” to “join”
- [x] in signup form, change “Login” to “Log In” (for both header button)
- [ ] Consistency pass

## Responsive / mobile
- [x] Match width of "Join" to "Log In" buttons
- [x] Match width of "Join" to "Learn More" buttons

**Comment by dzucconi** [comment]
A comment I have now is it looks weirdly off-center now that the title isn't there.

**Comment by dzucconi** [comment]
So...

**Comment by dzucconi** [comment]
Deploy?

**Comment by csherron** [comment]
- [ ] header: change “Join Login” to “Join or Log In”
- [ ] get rid of “updated X ago” in block captions
- [ ] in signup form, change “sign up” to “join” 
- [ ] in signup form, change “Login” to “Log In” (for both header button)
- [ ] “what is arena?” - make h5 and strong, with 2em padding instead of 1
- [ ] make video wrapper background white
- [ ] .utility—bordered give it a 1px border #c6c6c6
- [ ] video borders flicker and disappear on safari
- [ ] .HomeNext - bottom: 2em; make #c6c6c6
- [ ] ‘explore and collaborate’ section - replace still image with ‘onboarding-explore’ video, keep border
- [ ] ‘explore and collaborate’ section is wider set than the other sections
- [ ]

**Comment by csherron** [comment]
in responsive / mobile
match width of "Join" to "Log In" buttons
match width of "Join" to "Learn More" buttons
